base: 'https://typo3-14.ddev.site/de'
baseVariants:
  -
    base: 'https://typo3-14.ddev.site/'
    condition: 'applicationContext == "Development"'
dependencies:
  - typo314/setup-package
  - typo3/fluid-styled-content
  - typo3/seo-sitemap
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /en/
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
    hreflang: ''
    websiteTitle: TYPO3-14-EN
  -
    title: Deutsch
    enabled: true
    locale: de_DE.utf8
    hreflang: de-DE
    base: /
    websiteTitle: TYPO3-14-DE
    navigationTitle: Deutsch
    fallbackType: strict
    fallbacks: ''
    flag: de
    languageId: 1
rootPageId: 1
websiteTitle: ''
