base: /
dependencies:
  - typo314/setup-package
  - typo3/fluid-styled-content
languages:
  -
    title: Deutsch
    enabled: true
    locale: de_DE.utf8
    hreflang: de-DE
    base: /
    websiteTitle: ''
    navigationTitle: Deutsch
    flag: de
    languageId: 0
  -
    title: English
    enabled: true
    locale: en_GB.utf8
    hreflang: en-GB
    base: /en/
    websiteTitle: Homepage-Eng
    navigationTitle: English
    fallbackType: fallback
    fallbacks: ''
    flag: gb
    languageId: 1
rootPageId: 7
websiteTitle: ''
