name: typo3-14/bttabstoaccordion
title: typo3-14/bttabstoaccordion
description: 'Tabs to Accordion mit Bootstrap 5.3'
saveAndClose: true
prefixFields: true
prefixType: full
basics:
  - typo3-14/Accordionsettings
  - typo3-14/Tabssettings
  - typo3-14/Appearance
  - typo3-14/Links
group: ContentBlocks
fields:
  - identifier: backendheader
    label: Pluginbeschreibung f√ºr TYPO3 BE
    type: Text
  - identifier: tab_2
    type: Tab
    label: Tab/Accordion Items
  - identifier: palette_42
    type: Palette
  - identifier: tabtoaccordionsets
    type: Collection
    label: Einzelne TabToAccordionitem anlegen
    foreign_table: tt_content
    allowedRecordTypes:
      - typo3-14_textimage