td:
   #theme- or packagename - used in some typoscript files
  themeName: setup_package
  # company name
  companyName: Business Inc. All rights Reserved
  configHeaderComment: Technische Umsetzung - Business Inc. All rights Reserved
extKey:
  setup_package
resourcePath: 
  EXT:setup_package/Resources/
styles:
  templates:
    layoutRootPath: EXT:setup_package/Resources/Private/Templates/FluidStyledContent/Layouts/
    templateRootPath: EXT:setup_package/Resources/Private/Templates/FluidStyledContent/Templates/
    partialRootPath: EXT:setup_package/Resources/Private/Templates/FluidStyledContent/Partials/  
  content:
    textmedia:
    image:
      lazyLoading: lazy
      imageDecoding: async
      maxW: 1200
      maxWInText: 600
      linkWrap:
        lightboxEnabled: true
        lightboxCssClass: glightbox
        lightboxRelAttribute: noopener
    links:
      target:
      extTarget: _blank


  
