identifier: typo3-14/Cardgroupsettings
fields:
  - identifier: cardgroupsettings
    type: Tab
    label: Cardgroup Einstellungen Global
  - identifier: palette_number
    type: Palette
    label: Anzahl der Cards bestimmen
    description: Anzahl der Cards die innerhalb einer Reihe je Breakpoint(Device) angezeigt werden sollen.
    fields:
      - identifier: responsive_xs
        type: Select
        renderType: selectSingle
        label: Anzahl Cards - Mobile kleiner 576px
        items:
          - label: 'Auswählen'
            value: ''
          - label: '1'
            value: row-cols-1
          - label: '2'
            value: row-cols-2
      - identifier: responsive_sm
        type: Select
        renderType: selectSingle
        label: Anzahl Cards - Mobile sm > 576px 
        items:
          - label: 'Auswählen'
            value: ''
          - label: '2'
            value: row-cols-sm-2
          - label: '3'
            value: row-cols-sm-3
      - identifier: responsive_md
        type: Select
        renderType: selectSingle
        label: Anzahl Cards - Tablet md > 768px
        items:
          - label: 'Auswählen'
            value: ''
          - label: '2'
            value: row-cols-md-2                  
          - label: '3'
            value: row-cols-md-3
          - label: '4'
            value: row-cols-md-4
      - identifier: responsive_lg
        type: Select
        renderType: selectSingle
        label: Anzahl Cards - Desktop lg > 992px
        items:
          - label: 'Auswählen'
            value: ''      
          - label: '3'
            value: row-cols-lg-3
          - label: '4'
            value: row-cols-lg-4
          - label: '5'
            value: row-cols-lg-5
      - type: Linebreak
  - identifier: palette_distance
    type: Palette
    label: Abstand zwischen den einzelnen Cardelementen
    description: Horizontal und Vertikaler Zwischenraum zwischen den Cardelementen.
    fields:
      - identifier: cardspace_mobile
        type: Select
        renderType: selectSingle
        label: Abstand für Mobiledevices auswählen
        items:
          - label: 'Auswählen'
            value: ''
          - label: '10px'
            value: g-10
          - label: '15px'
            value: g-15
          - label: '20px'
            value: g-20
      - identifier: cardspace_tablet
        type: Select
        renderType: selectSingle
        label: Abstand für Tabletdevices auswählen
        items:
          - label: 'Auswählen'
            value: ''
          - label: '15px'
            value: g-ms-15
          - label: '20px'
            value: g-ms-20
          - label: '25px'
            value: g-ms-25
      - identifier: cardspace_desktop
        type: Select
        renderType: selectSingle
        label: Abstand für Desktopdevices auswählen
        items:
          - label: 'Auswählen'
            value: ''
          - label: '25px'
            value: g-md-25
          - label: '30px'
            value: g-md-30
          - label: '40px'
            value: g-md-40