name: typo3-14/bticonteaser
title: typo3-14/bticonteaser
description: Teasertext with Icon, link in different variations
basics:
  - typo3-14/Iconteasersettings
  - typo3-14/Appearance
  - typo3-14/Links
group: ContentBlocks
saveAndClose: true
prefixType: full
fields:
  - identifier: backendheader
    label: Pluginbeschreibung für TYPO3 BE
    type: Text
  - identifier: tab_1
    type: Tab
    label: Einzelne Teaser mit Icon anlegen      
  - identifier: palette_teaser
    type: Palette
    label: Einzelne Icon Teaser 
    fields:
      - identifier: collectionsets
        type: Collection
        label: Einzelne Teaser anlegen.
        appearance:
          collapseAll: true
          levelLinksPosition: both   
        fields:
          - identifier: teaserheadline
            type: Text
            label: Kurze Headline des Teasers
            description: Wird mit H4 angezeigt
            placeholder: Kurze Headline anlegen
          - identifier: svgidentifier
            type: Text
            label: Iconidentifier
            description: Der Identifier für den Icon kann von https://icons.getbootstrap.com/ kopiert werden. Einfach den Identifiertext unterhalb des gewünschten Icons kopieren und in das Eingabefeld eintragen
            placeholder: Beispiel - plus-square-fill
          - identifier: bodytextsimple
            label: Teasertext
            description: Kurzer Text.
            type: Textarea
            placeholder: Teasertext      
            enableRichtext: true
            richtextConfiguration: iconteaser
          - identifier: cta
            label: Linktext
            useExistingField: true
            type: Text
            placeholder: Call to Action Text
          - identifier: url
            label: Linkziel
            type: Link
            autocomplete: true
            allowedTypes:
              - page
              - url
              - file
            useExistingField: true
          - identifier: linklabel
            label: Nur Linklabel verlinken
            type: Checkbox
            renderType: checkboxLabeledToggle
            items:
              - label: 'Auswählen'
                labelChecked: 'Label ist verlinkt'
                labelUnchecked: 'Label verlinken'
                invertStateDisplay: false
          - identifier: linkcard
            label: Ganzen Teaser verlinken
            type: Checkbox
            renderType: checkboxLabeledToggle
            items:
              - label: 'Auswählen'
                labelChecked: 'Iconteaser ist verlinkt'
                labelUnchecked: 'Iconteaser verlinken'
                invertStateDisplay: false
