name: typo3-14/textimage
table: tx_typo3-14_textimage
title: Text mit Bild für Tabs und Accordion
prefixFields: true
prefixType: full
group: ContentBlocksHelper
security:
  ignorePageTypeRestriction: true
fields:
  - identifier: heading
    label: Tab-/Panelbeschriftung
    type: Text
    placeholder: Beschriftung eingeben
  - identifier: header
    label: Überschrift/Headline
    type: Text
  - identifier: bodytext
    label: Text eingeben
    type: Textarea
    enableRichtext: true
  - identifier: image
    label: Bild zum Text einfügen (max 1)
    type: File
    extendedPalette: true
    maxitems: 1
    allowed: common-image-types
    cropVariants:
      desktop:
        title: Desktop
        allowedAspectRatios:
          portrait:
            title: Portrait
            value: 3 / 4
          landscape:
            title: Landscape
            value: 4 / 3
      tablet:
        title: Tablet
        allowedAspectRatios:
          square:
            title: Square
            value: 1 / 1
      smartphone:
        title: Smartphone
        allowedAspectRatios:
          landscape:
            title: Landscape
            value: 4 / 3
          portrait:
            title: Portrait
            value: 3 / 4
  - identifier: imageposition
    label: Bildposition
    type: Select
    renderType: selectSingle
    items:
      - label: 'Links'
        value: left
      - label: 'Rechts'
        value: right